version: '3.1'

services:
  backend:
    container_name: mblabs_backend
    build: ./backend
    platform: linux/x86_64
    volumes:
      - ./backend:/app/backend
    ports:
      - 3999:3001
    restart: always
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASSWORD}"
      DB_HOST: mysqldb
      DB_PORT: 3306
    depends_on:
      mysqldb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true
    networks:
      - app-network

  mysqldb:
    image: mysql:8.0.21
    container_name: mblabs_db
    ports:
      - 3370:3306
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge